/**
 * Write your TypeScript in this file
 * Generated by: @slynova/symfony-encore
 */

const testButton = document.querySelector('.test')

testButton.addEventListener('click', () => {
  alert('click')
})
